services:
  nginx:
    image: nginx:1.31
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

  frontend:
    image: cicd-demo-frontend-dev
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: cicd-demo-frontend-dev

  backend:
    image: cicd-demo-backend-dev
    build:
      context: backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    container_name: cicd-demo-backend-dev
